on:
    push:
        branches:
            - master
            - main
        paths:
            - 'mongodb/**'
    pull_request:
        paths:
            - 'mongodb/**'
name: "Tests Mongodb"
jobs:
    Tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version:
                    - 1.20.x
                    - 1.21.x
                    - 1.22.x
        steps:
            -   name: Fetch Repository
                uses: actions/checkout@v4
            -   name: Install Go
                uses: actions/setup-go@v5
                with:
                    go-version: '${{ matrix.go-version }}'
            -   name: Run Test
                env:
                    TEST_MONGODB_IMAGE: docker.io/mongo:7
                run: cd ./mongodb && go test ./... -v -race

