on:
  push:
    branches:
      - master
      - main
    paths:
      - 'couchbase/**'
  pull_request:
    paths:
      - 'couchbase/**'
name: "Tests Couchbase"
jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.21.x
          - 1.22.x
          - 1.23.x
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
      -   name: Install Go
          uses: actions/setup-go@v5
          with:
            go-version: '${{ matrix.go-version }}'
      -   name: Run Test
          env:
            TEST_COUCHBASE_IMAGE: couchbase:enterprise-7.6.3
          run: cd ./couchbase && go test ./... -v -race
