on:
    push:
        branches:
            - master
            - main
        paths:
            - 'postgres/**'
    pull_request:
        paths:
            - 'postgres/**'
name: "Tests Postgres"
jobs:
    Tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version:
                    - 1.20.x
                    - 1.21.x
                    - 1.22.x
        steps:
            -   name: Fetch Repository
                uses: actions/checkout@v4
            -   name: Install Go
                uses: actions/setup-go@v5
                with:
                    go-version: '${{ matrix.go-version }}'
            -   name: Run Test
                env:
                    TEST_POSTGRES_IMAGE: "docker.io/postgres:16-alpine"
                run: cd ./postgres && go test ./... -v -race
